add header for http healthcheck
fatedier/frp pull request #4085
Opened 2024-03-19 10:26 UTC by KaiveYoung

### Healthcheck can't work when local web verify header

2024-03-19 11:42 UTC, fatedier requested changes

2024-03-19 11:42 UTC, fatedier commented on client/health/health.go
> +	req.Host = monitor.host
I have some misunderstandings about the configuration of the host in K8s. We should not add the host parameter here, but instead actively extract the host field from the header and assign it to req.Host.

```go
 req.Host = monitor.header.Get("Host")
```

2024-03-19 11:43 UTC, fatedier commented
By the way, you don't need to create a new PR, just push the new changes to the original branch.

2024-03-19 11:44 UTC, fatedier commented on pkg/config/v1/proxy.go
> +	Headers []HTTPHeader `json:"headers,omitempty"`
```suggestion
	HTTPHeaders []HTTPHeader `json:"httpHeaders,omitempty"`
```

2024-03-20 02:40 UTC, KaiveYoung commented
> By the way, you don't need to create a new PR, just push the new changes to the original branch.

New to PR, don’t know how to use it

2024-03-20 06:57 UTC, fatedier approved these changes

2024-03-20 06:58 UTC, merged